name: CI (monorepo)

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  client:
    name: Client (frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install client deps
        working-directory: client
        run: npm ci

      - name: Lint client (if available)
        working-directory: client
        run: npm run lint --if-present

      - name: Test client
        working-directory: client
        run: npm test

      - name: Build client
        working-directory: client
        run: npm run build --if-present

      - name: Upload client build
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: client/build # or client/dist depending on your app

  server:
    name: Server (backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install server deps
        working-directory: server
        run: npm ci

      - name: Lint server (if available)
        working-directory: server
        run: npm run lint --if-present

      - name: Test server
        working-directory: server
        run: npm test

      - name: Build server
        working-directory: server
        run: npm run build --if-present

      - name: Upload server build
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: server/dist
